WARNING 2018-08-31 09:38:52,726 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 09:42:45,075 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/Hellocial_0_1/urls.py", line 19, in <module>
    from apps.users.views import SearchResultView
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 21, in <module>
    from tel_apps.gen_script import GenTask
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 4, in <module>
    from tel_apps.base.base_activity import BaseActivity
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/base/base_activity.py", line 4, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named 'selenium'
WARNING 2018-08-31 09:45:52,680 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 09:45:52,680 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 16, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 35, in get_classes
    for file in os.listdir(os.path.join(dir_path, self.app_code)):
FileNotFoundError: [Errno 2] No such file or directory: '/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt'
WARNING 2018-08-31 09:47:17,619 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 09:47:17,622 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 16, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 39, in get_classes
    module = importlib.import_module(module_path)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt/article_activity.py", line 4, in <module>
    import settings
ImportError: No module named 'settings'
WARNING 2018-08-31 09:56:14,643 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 09:56:14,645 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 16, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 39, in get_classes
    module = importlib.import_module(module_path)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt/article_activity.py", line 3, in <module>
    from base.base_activity import BaseActivity
ImportError: No module named 'base'
WARNING 2018-08-31 09:58:31,219 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 09:58:31,220 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 20, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 43, in get_classes
    module = importlib.import_module(module_path)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt/article_activity.py", line 3, in <module>
    from base.base_activity import BaseActivity
ImportError: No module named 'base'
WARNING 2018-08-31 10:02:21,384 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:02:21,386 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 20, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 43, in get_classes
    module = importlib.import_module(module_path)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt/article_activity.py", line 3, in <module>
    from base.base_activity import BaseActivity
ImportError: No module named 'base'
WARNING 2018-08-31 10:03:34,420 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:03:34,421 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 20, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 43, in get_classes
    module = importlib.import_module(module_path)
  File "/home/python/.virtualenvs/dailyfresh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/jrtt/article_activity.py", line 3, in <module>
    from base.base_activity import BaseActivity
ImportError: No module named 'base'
WARNING 2018-08-31 10:04:36,059 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:04:36,064 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 20, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 48, in get_classes
    if issubclass(obj, BaseActivity):
TypeError: issubclass() arg 1 must be a class
WARNING 2018-08-31 10:04:45,070 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:04:45,072 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 20, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 48, in get_classes
    if issubclass(obj, BaseActivity):
TypeError: issubclass() arg 1 must be a class
WARNING 2018-08-31 10:05:55,334 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:05:55,335 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 21, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 49, in get_classes
    if issubclass(obj, BaseActivity):
TypeError: issubclass() arg 1 must be a class
WARNING 2018-08-31 10:07:01,767 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:07:01,768 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 21, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 49, in get_classes
    if issubclass(BaseActivity,obj):
TypeError: issubclass() arg 2 must be a class or tuple of classes
WARNING 2018-08-31 10:19:46,520 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:21:08,198 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 21, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 49, in get_classes
    if issubclass(BaseActivity,obj):
TypeError: issubclass() arg 2 must be a class or tuple of classes
WARNING 2018-08-31 10:22:47,611 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:23:53,405 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1457, in post
    gen_task = GenTask(fornum_code, app_task)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 21, in __init__
    self.get_classes()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 51, in get_classes
    if issubclass(BaseActivity,obj):
TypeError: issubclass() arg 2 must be a class or tuple of classes
WARNING 2018-08-31 10:25:31,432 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
WARNING 2018-08-31 10:26:20,108 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
ERROR 2018-08-31 10:27:39,187 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 256: Internal Server Error: /users/app/phone/login
Traceback (most recent call last):
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py", line 1459, in post
    if not gen_task.start():
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 98, in start
    instances_objs = self.get_current_task_obj()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/gen_script.py", line 67, in get_current_task_obj
    instance_obj = cls()
  File "/home/python/Desktop/Hellocial/Hellocial_0_1/tel_apps/base/base_activity.py", line 14, in __init__
    self.driver = kwargs['driver']
KeyError: 'driver'
WARNING 2018-08-31 10:35:23,586 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1453: JAKE没有隶属关系记录
